### ISSUE TITLE
Additions to the V2 on-device API should be made

### ISSUE THREAD

**Issue by CameronDiver** [balena-os/balena-supervisor#685]
This is an issue to track the various upgrades which will be made to the V2 API. Any suggestions should be added to this issue too.

Currently, we have a status endpoint, which supports multicontainer applications, but only that.

Planned upgrades:
- [ ] Restarting individual services on device
- [ ] Entering/exiting offline mode (from https://github.com/resin-io/resin-supervisor/issues/686)
- [ ] Entering/exiting local mode
- [ ] Allow the setting of device location (from: https://github.com/resin-io/resin-supervisor/issues/391)
- [ ] Allow the changing of device env vars (from: https://github.com/resin-io/resin-supervisor/issues/443)
- [ ] Allow retrieving and managing of device tags (from: https://github.com/resin-io/resin-supervisor/issues/542)
- [ ] Exposing device ID from an endpoint (from: https://github.com/resin-io/resin-supervisor/issues/276)
- [ ] Ability to edit network configurations
- [ ] The reporting of `CONFIG` variables

cc @shaunmulligan @alisondavis17

**Comment by shaunmulligan** [comment]
@CameronDiver this all sounds awesome. I think adding the network configuration stuff would be awesome too. I would guess we would be able to have both configuration from the UI and locally and use the same implementation on the supervisor i guess?

**Comment by alisondavis17** [comment]
yay for the network configuration stuff!
